backend:
  name: github
  repo: florisre/VitePress-with-Netlify-CMS
media_folder: "docs/public/media"
public_folder: "/media"
publish_mode: editorial_workflow
collections:
  - label: "Home"
    name: "home"
    files:
      - label: "Homepage"
        name: "homepage"
        file: "docs/index.md"
        delete: false
        fields:
          - { label: "Home", name: "home", widget: "hidden", default: true }
          - {
              label: "Hero image",
              name: "heroImage",
              widget: "image",
              required: false,
            }
          - { label: "Hero text", name: "heroText", widget: "string" }
          - {
              label: "Tagline",
              name: "tagline",
              widget: "string",
              required: false,
            }
          - { label: "Action text", name: "actionText", widget: "string" }
          - { label: "Action link", name: "actionLink", widget: "string" }
          - label: Features
            name: features
            widget: list
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Details", name: "details", widget: "string" }
          - {
              label: "Footer",
              name: "footer",
              widget: "string",
              required: false,
            }
          - { label: "Body", name: body, widget: markdown, required: false }
  - label: "Post"
    name: "posts"
    folder: "docs/post"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Meta description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "protkolle" # Used in routes, e.g., /admin/collections/songs
    label: "Protokolle" # Used in the UI
    label_singular: Protokoll
    folder: "docs/protokolle" # The path to the folder where the documents are stored
    nested: # adding a nested object will show the collection folder structure
      depth: 2 # max depth to show in the collection tree
    create: true # Allow users to create new documents in this collection
    slug: "{{date}}/index" # Filename template # Outputs sun-apr-02-2023-01-13-17-gmt-0300-east-africa-time (not ideal but is dynamic to date - only at creation not at editing)
    summary: "{{dirname}} . Zuletzt aktualisiert: {{commit_date}}"
    preview_path: protokolle/{{date}}
    fields: # The fields for each document, usually in front matter
      - {label: "lastUpdated", name: "lastUpdated", widget: "hidden", default: true}
      - {label: "contributors", hint: "Show contributors at the footer", name: "contributors", widget: "boolean", default: true}
      - {label: "Show icon for external links", name: "externalLinkIcon", widget: "boolean", default: false}
      - label: "Entry Date"
        name: "date"
        widget: "datetime"
        format: 'YYYY-MM-DD'
        time_format: false
        required: true
      - {label: "Body", name: "body", widget: "markdown", default: "# Song title (Composer/ Artist)"}
